apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      serviceAccountName: accessos
      imagePullSecrets:
        - name: regcred
      containers:
        - name: admin
          image: accessos/admin:06e3c21df
          resources:
            limits:
              memory: 4096M
              cpu: "1"
            requests:
              cpu: 400m
              memory: 4096M
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DEPLOYMENT_VERSION
              value: "06e3c21df"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=4096"
            - name: DEBUG
              value: "false"
            - name: LOGGING_LEVEL
              value: "info"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: postgres-database
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: postgres-port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: postgres-user
            - name: COOKIE_SECURE
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: cookie-secure
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: postgres-password
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: redis-host
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: redis-username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: redis-password
            - name: REDIS_DB
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: redis-db
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: redis-port
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: domain
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin
  name: admin
spec:
  type: NodePort
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
  selector:
    app: admin
