apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scheduler 
  name: scheduler 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler 
  template:
    metadata:
      labels:
        app: scheduler 
    spec:
      serviceAccountName: accessos
      imagePullSecrets:
        - name: regcred
      containers:
        - name: scheduler 
          image: accessos/scheduler:61351c23b
          resources:
            limits:
              memory: 2048M
              cpu: "2"
            requests:
              cpu: 1000m
              memory: 1024M
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DEPLOYMENT_VERSION
              value: "61351c23b"
            - name: DEBUG
              value: "false"
            - name: LOGGING_LEVEL
              value: "info"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: postgres-database
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: postgres-port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: postgres-password
            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: domain
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: redis-host
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: redis-username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: redis-password
            - name: REDIS_DB
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: redis-db
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: accessos-secrets
                  key: redis-port
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?statement_cache_size=0"
            - name: GOOGLE_OAUTH_REDIRECT_URL
              value: "https://$(DOMAIN)/auth/callback"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: scheduler 
  name: scheduler 
spec:
  type: ClusterIP 
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: scheduler 
